name: flutter_auth_provider
description: Simple, customizable authentication manager for Flutter
version: 0.0.4
homepage: https://github.com/iamchathu/flutter_auth_provider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  flutter_lints: ^2.0.1

flutter:
